// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetDestinationDatabend
    {
        /// <summary>
        /// DestinationDatabend DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myDestinationDatabend = Airbyte.GetDestinationDatabend.Invoke(new()
        ///     {
        ///         DestinationId = "...my_destination_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetDestinationDatabendResult> InvokeAsync(GetDestinationDatabendArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDestinationDatabendResult>("airbyte:index/getDestinationDatabend:getDestinationDatabend", args ?? new GetDestinationDatabendArgs(), options.WithDefaults());

        /// <summary>
        /// DestinationDatabend DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myDestinationDatabend = Airbyte.GetDestinationDatabend.Invoke(new()
        ///     {
        ///         DestinationId = "...my_destination_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetDestinationDatabendResult> Invoke(GetDestinationDatabendInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDestinationDatabendResult>("airbyte:index/getDestinationDatabend:getDestinationDatabend", args ?? new GetDestinationDatabendInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDestinationDatabendArgs : global::Pulumi.InvokeArgs
    {
        [Input("destinationId", required: true)]
        public string DestinationId { get; set; } = null!;

        public GetDestinationDatabendArgs()
        {
        }
        public static new GetDestinationDatabendArgs Empty => new GetDestinationDatabendArgs();
    }

    public sealed class GetDestinationDatabendInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("destinationId", required: true)]
        public Input<string> DestinationId { get; set; } = null!;

        public GetDestinationDatabendInvokeArgs()
        {
        }
        public static new GetDestinationDatabendInvokeArgs Empty => new GetDestinationDatabendInvokeArgs();
    }


    [OutputType]
    public sealed class GetDestinationDatabendResult
    {
        /// <summary>
        /// The values required to configure the destination. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        public readonly string DestinationId;
        public readonly string DestinationType;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetDestinationDatabendResult(
            string configuration,

            string destinationId,

            string destinationType,

            string id,

            string name,

            string workspaceId)
        {
            Configuration = configuration;
            DestinationId = destinationId;
            DestinationType = destinationType;
            Id = id;
            Name = name;
            WorkspaceId = workspaceId;
        }
    }
}
