// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetDestinationAwsDatalake
    {
        /// <summary>
        /// DestinationAwsDatalake DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myDestinationAwsdatalake = Airbyte.GetDestinationAwsDatalake.Invoke(new()
        ///     {
        ///         DestinationId = "...my_destination_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetDestinationAwsDatalakeResult> InvokeAsync(GetDestinationAwsDatalakeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDestinationAwsDatalakeResult>("airbyte:index/getDestinationAwsDatalake:getDestinationAwsDatalake", args ?? new GetDestinationAwsDatalakeArgs(), options.WithDefaults());

        /// <summary>
        /// DestinationAwsDatalake DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myDestinationAwsdatalake = Airbyte.GetDestinationAwsDatalake.Invoke(new()
        ///     {
        ///         DestinationId = "...my_destination_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetDestinationAwsDatalakeResult> Invoke(GetDestinationAwsDatalakeInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDestinationAwsDatalakeResult>("airbyte:index/getDestinationAwsDatalake:getDestinationAwsDatalake", args ?? new GetDestinationAwsDatalakeInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDestinationAwsDatalakeArgs : global::Pulumi.InvokeArgs
    {
        [Input("destinationId", required: true)]
        public string DestinationId { get; set; } = null!;

        public GetDestinationAwsDatalakeArgs()
        {
        }
        public static new GetDestinationAwsDatalakeArgs Empty => new GetDestinationAwsDatalakeArgs();
    }

    public sealed class GetDestinationAwsDatalakeInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("destinationId", required: true)]
        public Input<string> DestinationId { get; set; } = null!;

        public GetDestinationAwsDatalakeInvokeArgs()
        {
        }
        public static new GetDestinationAwsDatalakeInvokeArgs Empty => new GetDestinationAwsDatalakeInvokeArgs();
    }


    [OutputType]
    public sealed class GetDestinationAwsDatalakeResult
    {
        /// <summary>
        /// The values required to configure the destination. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        public readonly string DestinationId;
        public readonly string DestinationType;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetDestinationAwsDatalakeResult(
            string configuration,

            string destinationId,

            string destinationType,

            string id,

            string name,

            string workspaceId)
        {
            Configuration = configuration;
            DestinationId = destinationId;
            DestinationType = destinationType;
            Id = id;
            Name = name;
            WorkspaceId = workspaceId;
        }
    }
}
