// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceWikipediaPageviews
    {
        /// <summary>
        /// SourceWikipediaPageviews DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceWikipediapageviews = Airbyte.GetSourceWikipediaPageviews.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourceWikipediaPageviewsResult> InvokeAsync(GetSourceWikipediaPageviewsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceWikipediaPageviewsResult>("airbyte:index/getSourceWikipediaPageviews:getSourceWikipediaPageviews", args ?? new GetSourceWikipediaPageviewsArgs(), options.WithDefaults());

        /// <summary>
        /// SourceWikipediaPageviews DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceWikipediapageviews = Airbyte.GetSourceWikipediaPageviews.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourceWikipediaPageviewsResult> Invoke(GetSourceWikipediaPageviewsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceWikipediaPageviewsResult>("airbyte:index/getSourceWikipediaPageviews:getSourceWikipediaPageviews", args ?? new GetSourceWikipediaPageviewsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceWikipediaPageviewsArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceWikipediaPageviewsArgs()
        {
        }
        public static new GetSourceWikipediaPageviewsArgs Empty => new GetSourceWikipediaPageviewsArgs();
    }

    public sealed class GetSourceWikipediaPageviewsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceWikipediaPageviewsInvokeArgs()
        {
        }
        public static new GetSourceWikipediaPageviewsInvokeArgs Empty => new GetSourceWikipediaPageviewsInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceWikipediaPageviewsResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceWikipediaPageviewsResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
