// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceGreenhouse
    {
        /// <summary>
        /// SourceGreenhouse DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceGreenhouse = Airbyte.GetSourceGreenhouse.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourceGreenhouseResult> InvokeAsync(GetSourceGreenhouseArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceGreenhouseResult>("airbyte:index/getSourceGreenhouse:getSourceGreenhouse", args ?? new GetSourceGreenhouseArgs(), options.WithDefaults());

        /// <summary>
        /// SourceGreenhouse DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceGreenhouse = Airbyte.GetSourceGreenhouse.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourceGreenhouseResult> Invoke(GetSourceGreenhouseInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceGreenhouseResult>("airbyte:index/getSourceGreenhouse:getSourceGreenhouse", args ?? new GetSourceGreenhouseInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceGreenhouseArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceGreenhouseArgs()
        {
        }
        public static new GetSourceGreenhouseArgs Empty => new GetSourceGreenhouseArgs();
    }

    public sealed class GetSourceGreenhouseInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceGreenhouseInvokeArgs()
        {
        }
        public static new GetSourceGreenhouseInvokeArgs Empty => new GetSourceGreenhouseInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceGreenhouseResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceGreenhouseResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
