// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceGoogleAds
    {
        /// <summary>
        /// SourceGoogleAds DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceGoogleads = Airbyte.GetSourceGoogleAds.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourceGoogleAdsResult> InvokeAsync(GetSourceGoogleAdsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceGoogleAdsResult>("airbyte:index/getSourceGoogleAds:getSourceGoogleAds", args ?? new GetSourceGoogleAdsArgs(), options.WithDefaults());

        /// <summary>
        /// SourceGoogleAds DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceGoogleads = Airbyte.GetSourceGoogleAds.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourceGoogleAdsResult> Invoke(GetSourceGoogleAdsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceGoogleAdsResult>("airbyte:index/getSourceGoogleAds:getSourceGoogleAds", args ?? new GetSourceGoogleAdsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceGoogleAdsArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceGoogleAdsArgs()
        {
        }
        public static new GetSourceGoogleAdsArgs Empty => new GetSourceGoogleAdsArgs();
    }

    public sealed class GetSourceGoogleAdsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceGoogleAdsInvokeArgs()
        {
        }
        public static new GetSourceGoogleAdsInvokeArgs Empty => new GetSourceGoogleAdsInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceGoogleAdsResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceGoogleAdsResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
