// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceSpacexApi
    {
        /// <summary>
        /// SourceSpacexAPI DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceSpacexapi = Airbyte.GetSourceSpacexApi.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourceSpacexApiResult> InvokeAsync(GetSourceSpacexApiArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceSpacexApiResult>("airbyte:index/getSourceSpacexApi:getSourceSpacexApi", args ?? new GetSourceSpacexApiArgs(), options.WithDefaults());

        /// <summary>
        /// SourceSpacexAPI DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceSpacexapi = Airbyte.GetSourceSpacexApi.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourceSpacexApiResult> Invoke(GetSourceSpacexApiInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceSpacexApiResult>("airbyte:index/getSourceSpacexApi:getSourceSpacexApi", args ?? new GetSourceSpacexApiInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceSpacexApiArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceSpacexApiArgs()
        {
        }
        public static new GetSourceSpacexApiArgs Empty => new GetSourceSpacexApiArgs();
    }

    public sealed class GetSourceSpacexApiInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceSpacexApiInvokeArgs()
        {
        }
        public static new GetSourceSpacexApiInvokeArgs Empty => new GetSourceSpacexApiInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceSpacexApiResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceSpacexApiResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
