// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceYoutubeAnalytics
    {
        /// <summary>
        /// SourceYoutubeAnalytics DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceYoutubeanalytics = Airbyte.GetSourceYoutubeAnalytics.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourceYoutubeAnalyticsResult> InvokeAsync(GetSourceYoutubeAnalyticsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceYoutubeAnalyticsResult>("airbyte:index/getSourceYoutubeAnalytics:getSourceYoutubeAnalytics", args ?? new GetSourceYoutubeAnalyticsArgs(), options.WithDefaults());

        /// <summary>
        /// SourceYoutubeAnalytics DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceYoutubeanalytics = Airbyte.GetSourceYoutubeAnalytics.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourceYoutubeAnalyticsResult> Invoke(GetSourceYoutubeAnalyticsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceYoutubeAnalyticsResult>("airbyte:index/getSourceYoutubeAnalytics:getSourceYoutubeAnalytics", args ?? new GetSourceYoutubeAnalyticsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceYoutubeAnalyticsArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceYoutubeAnalyticsArgs()
        {
        }
        public static new GetSourceYoutubeAnalyticsArgs Empty => new GetSourceYoutubeAnalyticsArgs();
    }

    public sealed class GetSourceYoutubeAnalyticsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceYoutubeAnalyticsInvokeArgs()
        {
        }
        public static new GetSourceYoutubeAnalyticsInvokeArgs Empty => new GetSourceYoutubeAnalyticsInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceYoutubeAnalyticsResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceYoutubeAnalyticsResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
