// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceZendeskSunshine
    {
        /// <summary>
        /// SourceZendeskSunshine DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceZendesksunshine = Airbyte.GetSourceZendeskSunshine.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourceZendeskSunshineResult> InvokeAsync(GetSourceZendeskSunshineArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceZendeskSunshineResult>("airbyte:index/getSourceZendeskSunshine:getSourceZendeskSunshine", args ?? new GetSourceZendeskSunshineArgs(), options.WithDefaults());

        /// <summary>
        /// SourceZendeskSunshine DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceZendesksunshine = Airbyte.GetSourceZendeskSunshine.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourceZendeskSunshineResult> Invoke(GetSourceZendeskSunshineInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceZendeskSunshineResult>("airbyte:index/getSourceZendeskSunshine:getSourceZendeskSunshine", args ?? new GetSourceZendeskSunshineInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceZendeskSunshineArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceZendeskSunshineArgs()
        {
        }
        public static new GetSourceZendeskSunshineArgs Empty => new GetSourceZendeskSunshineArgs();
    }

    public sealed class GetSourceZendeskSunshineInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceZendeskSunshineInvokeArgs()
        {
        }
        public static new GetSourceZendeskSunshineInvokeArgs Empty => new GetSourceZendeskSunshineInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceZendeskSunshineResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceZendeskSunshineResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
