// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourcePolygonStockApi
    {
        /// <summary>
        /// SourcePolygonStockAPI DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourcePolygonstockapi = Airbyte.GetSourcePolygonStockApi.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourcePolygonStockApiResult> InvokeAsync(GetSourcePolygonStockApiArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourcePolygonStockApiResult>("airbyte:index/getSourcePolygonStockApi:getSourcePolygonStockApi", args ?? new GetSourcePolygonStockApiArgs(), options.WithDefaults());

        /// <summary>
        /// SourcePolygonStockAPI DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourcePolygonstockapi = Airbyte.GetSourcePolygonStockApi.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourcePolygonStockApiResult> Invoke(GetSourcePolygonStockApiInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourcePolygonStockApiResult>("airbyte:index/getSourcePolygonStockApi:getSourcePolygonStockApi", args ?? new GetSourcePolygonStockApiInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourcePolygonStockApiArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourcePolygonStockApiArgs()
        {
        }
        public static new GetSourcePolygonStockApiArgs Empty => new GetSourcePolygonStockApiArgs();
    }

    public sealed class GetSourcePolygonStockApiInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourcePolygonStockApiInvokeArgs()
        {
        }
        public static new GetSourcePolygonStockApiInvokeArgs Empty => new GetSourcePolygonStockApiInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourcePolygonStockApiResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourcePolygonStockApiResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
