// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceGainsightPx
    {
        /// <summary>
        /// SourceGainsightPx DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceGainsightpx = Airbyte.GetSourceGainsightPx.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourceGainsightPxResult> InvokeAsync(GetSourceGainsightPxArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceGainsightPxResult>("airbyte:index/getSourceGainsightPx:getSourceGainsightPx", args ?? new GetSourceGainsightPxArgs(), options.WithDefaults());

        /// <summary>
        /// SourceGainsightPx DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceGainsightpx = Airbyte.GetSourceGainsightPx.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourceGainsightPxResult> Invoke(GetSourceGainsightPxInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceGainsightPxResult>("airbyte:index/getSourceGainsightPx:getSourceGainsightPx", args ?? new GetSourceGainsightPxInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceGainsightPxArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceGainsightPxArgs()
        {
        }
        public static new GetSourceGainsightPxArgs Empty => new GetSourceGainsightPxArgs();
    }

    public sealed class GetSourceGainsightPxInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceGainsightPxInvokeArgs()
        {
        }
        public static new GetSourceGainsightPxInvokeArgs Empty => new GetSourceGainsightPxInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceGainsightPxResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceGainsightPxResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
