// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceLinkedinAds
    {
        /// <summary>
        /// SourceLinkedinAds DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceLinkedinads = Airbyte.GetSourceLinkedinAds.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSourceLinkedinAdsResult> InvokeAsync(GetSourceLinkedinAdsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceLinkedinAdsResult>("airbyte:index/getSourceLinkedinAds:getSourceLinkedinAds", args ?? new GetSourceLinkedinAdsArgs(), options.WithDefaults());

        /// <summary>
        /// SourceLinkedinAds DataSource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Airbyte = Pulumi.Airbyte;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var mySourceLinkedinads = Airbyte.GetSourceLinkedinAds.Invoke(new()
        ///     {
        ///         SourceId = "...my_source_id...",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSourceLinkedinAdsResult> Invoke(GetSourceLinkedinAdsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceLinkedinAdsResult>("airbyte:index/getSourceLinkedinAds:getSourceLinkedinAds", args ?? new GetSourceLinkedinAdsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceLinkedinAdsArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceLinkedinAdsArgs()
        {
        }
        public static new GetSourceLinkedinAdsArgs Empty => new GetSourceLinkedinAdsArgs();
    }

    public sealed class GetSourceLinkedinAdsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceLinkedinAdsInvokeArgs()
        {
        }
        public static new GetSourceLinkedinAdsInvokeArgs Empty => new GetSourceLinkedinAdsInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceLinkedinAdsResult
    {
        /// <summary>
        /// The values required to configure the source. Parsed as JSON.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceLinkedinAdsResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
