// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationRedshiftConfigurationUploadingMethodAwss3Staging
    {
        /// <summary>
        /// This ID grants access to the above S3 staging bucket. Airbyte requires Read and Write permissions to the given bucket. See \n\nAWS docs\n\n on how to generate an access key ID and secret access key.
        /// </summary>
        public readonly string AccessKeyId;
        /// <summary>
        /// How to encrypt the staging data
        /// </summary>
        public readonly Outputs.DestinationRedshiftConfigurationUploadingMethodAwss3StagingEncryption? Encryption;
        /// <summary>
        /// Number of file buffers allocated for writing data. Increasing this number is beneficial for connections using Change Data Capture (CDC) and up to the number of streams within a connection. Increasing the number of file buffers past the maximum number of streams has deteriorating effects. Default: 10
        /// </summary>
        public readonly int? FileBufferCount;
        /// <summary>
        /// The pattern allows you to set the file-name format for the S3 staging file(s)
        /// </summary>
        public readonly string? FileNamePattern;
        /// <summary>
        /// Whether to delete the staging files from S3 after completing the sync. See \n\n docs\n\n for details. Default: true
        /// </summary>
        public readonly bool? PurgeStagingData;
        /// <summary>
        /// The name of the staging S3 bucket.
        /// </summary>
        public readonly string S3BucketName;
        /// <summary>
        /// The directory under the S3 bucket where data will be written. If not provided, then defaults to the root directory. See \n\npath's name recommendations\n\n for more details.
        /// </summary>
        public readonly string? S3BucketPath;
        /// <summary>
        /// The region of the S3 staging bucket. must be one of ["", "af-south-1", "ap-east-1", "ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-south-1", "ap-south-2", "ap-southeast-1", "ap-southeast-2", "ap-southeast-3", "ap-southeast-4", "ca-central-1", "ca-west-1", "cn-north-1", "cn-northwest-1", "eu-central-1", "eu-central-2", "eu-north-1", "eu-south-1", "eu-south-2", "eu-west-1", "eu-west-2", "eu-west-3", "il-central-1", "me-central-1", "me-south-1", "sa-east-1", "us-east-1", "us-east-2", "us-gov-east-1", "us-gov-west-1", "us-west-1", "us-west-2"]; Default: ""
        /// </summary>
        public readonly string? S3BucketRegion;
        /// <summary>
        /// The corresponding secret to the above access key id. See \n\nAWS docs\n\n on how to generate an access key ID and secret access key.
        /// </summary>
        public readonly string SecretAccessKey;

        [OutputConstructor]
        private DestinationRedshiftConfigurationUploadingMethodAwss3Staging(
            string accessKeyId,

            Outputs.DestinationRedshiftConfigurationUploadingMethodAwss3StagingEncryption? encryption,

            int? fileBufferCount,

            string? fileNamePattern,

            bool? purgeStagingData,

            string s3BucketName,

            string? s3BucketPath,

            string? s3BucketRegion,

            string secretAccessKey)
        {
            AccessKeyId = accessKeyId;
            Encryption = encryption;
            FileBufferCount = fileBufferCount;
            FileNamePattern = fileNamePattern;
            PurgeStagingData = purgeStagingData;
            S3BucketName = s3BucketName;
            S3BucketPath = s3BucketPath;
            S3BucketRegion = s3BucketRegion;
            SecretAccessKey = secretAccessKey;
        }
    }
}
