// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationKinesisConfiguration
    {
        /// <summary>
        /// Generate the AWS Access Key for current user.
        /// </summary>
        public readonly string AccessKey;
        /// <summary>
        /// Buffer size for storing kinesis records before being batch streamed. Default: 100
        /// </summary>
        public readonly int? BufferSize;
        /// <summary>
        /// AWS Kinesis endpoint.
        /// </summary>
        public readonly string Endpoint;
        /// <summary>
        /// The AWS Private Key - a string of numbers and letters that are unique for each account, also known as a "recovery phrase".
        /// </summary>
        public readonly string PrivateKey;
        /// <summary>
        /// AWS region. Your account determines the Regions that are available to you.
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// Number of shards to which the data should be streamed. Default: 5
        /// </summary>
        public readonly int? ShardCount;

        [OutputConstructor]
        private DestinationKinesisConfiguration(
            string accessKey,

            int? bufferSize,

            string endpoint,

            string privateKey,

            string region,

            int? shardCount)
        {
            AccessKey = accessKey;
            BufferSize = bufferSize;
            Endpoint = endpoint;
            PrivateKey = privateKey;
            Region = region;
            ShardCount = shardCount;
        }
    }
}
