// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationRedshiftConfiguration
    {
        /// <summary>
        /// Name of the database.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Disable Writing Final Tables. WARNING! The data format in *airbyte*data is likely stable but there are no guarantees that other metadata columns will remain the same in future versions. Default: false
        /// </summary>
        public readonly bool? DisableTypeDedupe;
        /// <summary>
        /// When enabled your data will load into your final tables incrementally while your data is still being synced. When Disabled (the default), your data loads into your final tables once at the end of a sync. Note that this option only applies if you elect to create Final tables. Default: false
        /// </summary>
        public readonly bool? EnableIncrementalFinalTableUpdates;
        /// <summary>
        /// Host Endpoint of the Redshift Cluster (must include the cluster-id, region and end with .redshift.amazonaws.com)
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Additional properties to pass to the JDBC URL string when connecting to the database formatted as 'key=value' pairs separated by the symbol '&amp;'. (example: key1=value1&amp;key2=value2&amp;key3=value3).
        /// </summary>
        public readonly string? JdbcUrlParams;
        /// <summary>
        /// Password associated with the username.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// Port of the database. Default: 5439
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// The schema to write raw tables into
        /// </summary>
        public readonly string? RawDataSchema;
        /// <summary>
        /// The default schema tables are written to if the source does not specify a namespace. Unless specifically configured, the usual value for this field is "public". Default: "public"
        /// </summary>
        public readonly string? Schema;
        /// <summary>
        /// Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use.
        /// </summary>
        public readonly Outputs.DestinationRedshiftConfigurationTunnelMethod? TunnelMethod;
        /// <summary>
        /// The way data will be uploaded to Redshift.
        /// </summary>
        public readonly Outputs.DestinationRedshiftConfigurationUploadingMethod? UploadingMethod;
        /// <summary>
        /// Username to use to access the database.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private DestinationRedshiftConfiguration(
            string database,

            bool? disableTypeDedupe,

            bool? enableIncrementalFinalTableUpdates,

            string host,

            string? jdbcUrlParams,

            string password,

            int? port,

            string? rawDataSchema,

            string? schema,

            Outputs.DestinationRedshiftConfigurationTunnelMethod? tunnelMethod,

            Outputs.DestinationRedshiftConfigurationUploadingMethod? uploadingMethod,

            string username)
        {
            Database = database;
            DisableTypeDedupe = disableTypeDedupe;
            EnableIncrementalFinalTableUpdates = enableIncrementalFinalTableUpdates;
            Host = host;
            JdbcUrlParams = jdbcUrlParams;
            Password = password;
            Port = port;
            RawDataSchema = rawDataSchema;
            Schema = schema;
            TunnelMethod = tunnelMethod;
            UploadingMethod = uploadingMethod;
            Username = username;
        }
    }
}
