// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationSnowflakeConfiguration
    {
        public readonly Outputs.DestinationSnowflakeConfigurationCredentials? Credentials;
        /// <summary>
        /// Enter the name of the \n\ndatabase\n\n you want to sync data into
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Disable Writing Final Tables. WARNING! The data format in *airbyte*data is likely stable but there are no guarantees that other metadata columns will remain the same in future versions. Default: false
        /// </summary>
        public readonly bool? DisableTypeDedupe;
        /// <summary>
        /// When enabled your data will load into your final tables incrementally while your data is still being synced. When Disabled (the default), your data loads into your final tables once at the end of a sync. Note that this option only applies if you elect to create Final tables. Default: false
        /// </summary>
        public readonly bool? EnableIncrementalFinalTableUpdates;
        /// <summary>
        /// Enter your Snowflake account's \n\nlocator\n\n (in the format \n\n.\n\n.\n\n.snowflakecomputing.com)
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Enter the additional properties to pass to the JDBC URL string when connecting to the database (formatted as key=value pairs separated by the symbol &amp;). Example: key1=value1&amp;key2=value2&amp;key3=value3
        /// </summary>
        public readonly string? JdbcUrlParams;
        /// <summary>
        /// The schema to write raw tables into (default: airbyte_internal)
        /// </summary>
        public readonly string? RawDataSchema;
        /// <summary>
        /// Enter the \n\nrole\n\n that you want to use to access Snowflake
        /// </summary>
        public readonly string Role;
        /// <summary>
        /// Enter the name of the default \n\nschema\n\n
        /// </summary>
        public readonly string Schema;
        /// <summary>
        /// Enter the name of the user you want to use to access the database
        /// </summary>
        public readonly string Username;
        /// <summary>
        /// Enter the name of the \n\nwarehouse\n\n that you want to sync data into
        /// </summary>
        public readonly string Warehouse;

        [OutputConstructor]
        private DestinationSnowflakeConfiguration(
            Outputs.DestinationSnowflakeConfigurationCredentials? credentials,

            string database,

            bool? disableTypeDedupe,

            bool? enableIncrementalFinalTableUpdates,

            string host,

            string? jdbcUrlParams,

            string? rawDataSchema,

            string role,

            string schema,

            string username,

            string warehouse)
        {
            Credentials = credentials;
            Database = database;
            DisableTypeDedupe = disableTypeDedupe;
            EnableIncrementalFinalTableUpdates = enableIncrementalFinalTableUpdates;
            Host = host;
            JdbcUrlParams = jdbcUrlParams;
            RawDataSchema = rawDataSchema;
            Role = role;
            Schema = schema;
            Username = username;
            Warehouse = warehouse;
        }
    }
}
