// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationVerticaConfiguration
    {
        /// <summary>
        /// Name of the database.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Hostname of the database.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Additional properties to pass to the JDBC URL string when connecting to the database formatted as 'key=value' pairs separated by the symbol '&amp;'. (example: key1=value1&amp;key2=value2&amp;key3=value3).
        /// </summary>
        public readonly string? JdbcUrlParams;
        /// <summary>
        /// Password associated with the username.
        /// </summary>
        public readonly string? Password;
        /// <summary>
        /// Port of the database. Default: 5433
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// Schema for vertica destination
        /// </summary>
        public readonly string Schema;
        /// <summary>
        /// Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use.
        /// </summary>
        public readonly Outputs.DestinationVerticaConfigurationTunnelMethod? TunnelMethod;
        /// <summary>
        /// Username to use to access the database.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private DestinationVerticaConfiguration(
            string database,

            string host,

            string? jdbcUrlParams,

            string? password,

            int? port,

            string schema,

            Outputs.DestinationVerticaConfigurationTunnelMethod? tunnelMethod,

            string username)
        {
            Database = database;
            Host = host;
            JdbcUrlParams = jdbcUrlParams;
            Password = password;
            Port = port;
            Schema = schema;
            TunnelMethod = tunnelMethod;
            Username = username;
        }
    }
}
