// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationS3Configuration
    {
        /// <summary>
        /// The access key ID to access the S3 bucket. Airbyte requires Read and Write permissions to the given bucket. Read more \n\nhere\n\n.
        /// </summary>
        public readonly string? AccessKeyId;
        /// <summary>
        /// The pattern allows you to set the file-name format for the S3 staging file(s)
        /// </summary>
        public readonly string? FileNamePattern;
        /// <summary>
        /// Format of the data output. See \n\nhere\n\n for more details
        /// </summary>
        public readonly Outputs.DestinationS3ConfigurationFormat Format;
        /// <summary>
        /// The name of the S3 bucket. Read more \n\nhere\n\n.
        /// </summary>
        public readonly string S3BucketName;
        /// <summary>
        /// Directory under the S3 bucket where data will be written. Read more \n\nhere\n\n
        /// </summary>
        public readonly string S3BucketPath;
        /// <summary>
        /// The region of the S3 bucket. See \n\nhere\n\n for all region codes. must be one of ["", "af-south-1", "ap-east-1", "ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-south-1", "ap-south-2", "ap-southeast-1", "ap-southeast-2", "ap-southeast-3", "ap-southeast-4", "ca-central-1", "ca-west-1", "cn-north-1", "cn-northwest-1", "eu-central-1", "eu-central-2", "eu-north-1", "eu-south-1", "eu-south-2", "eu-west-1", "eu-west-2", "eu-west-3", "il-central-1", "me-central-1", "me-south-1", "sa-east-1", "us-east-1", "us-east-2", "us-gov-east-1", "us-gov-west-1", "us-west-1", "us-west-2"]; Default: ""
        /// </summary>
        public readonly string? S3BucketRegion;
        /// <summary>
        /// Your S3 endpoint url. Read more \n\nhere\n\n. Default: ""
        /// </summary>
        public readonly string? S3Endpoint;
        /// <summary>
        /// Format string on how data will be organized inside the S3 bucket directory. Read more \n\nhere\n\n
        /// </summary>
        public readonly string? S3PathFormat;
        /// <summary>
        /// The corresponding secret to the access key ID. Read more \n\nhere\n\n
        /// </summary>
        public readonly string? SecretAccessKey;

        [OutputConstructor]
        private DestinationS3Configuration(
            string? accessKeyId,

            string? fileNamePattern,

            Outputs.DestinationS3ConfigurationFormat format,

            string s3BucketName,

            string s3BucketPath,

            string? s3BucketRegion,

            string? s3Endpoint,

            string? s3PathFormat,

            string? secretAccessKey)
        {
            AccessKeyId = accessKeyId;
            FileNamePattern = fileNamePattern;
            Format = format;
            S3BucketName = s3BucketName;
            S3BucketPath = s3BucketPath;
            S3BucketRegion = s3BucketRegion;
            S3Endpoint = s3Endpoint;
            S3PathFormat = s3PathFormat;
            SecretAccessKey = secretAccessKey;
        }
    }
}
