// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceMongodbV2Configuration
    {
        /// <summary>
        /// Configures the MongoDB cluster type.
        /// </summary>
        public readonly Outputs.SourceMongodbV2ConfigurationDatabaseConfig DatabaseConfig;
        /// <summary>
        /// The maximum number of documents to sample when attempting to discover the unique fields for a collection. Default: 10000
        /// </summary>
        public readonly int? DiscoverSampleSize;
        /// <summary>
        /// The amount of time the connector will wait when it launches to determine if there is new data to sync or not. Defaults to 300 seconds. Valid range: 120 seconds to 1200 seconds. Default: 300
        /// </summary>
        public readonly int? InitialWaitingSeconds;
        /// <summary>
        /// The size of the internal queue. This may interfere with memory consumption and efficiency of the connector, please be careful. Default: 10000
        /// </summary>
        public readonly int? QueueSize;

        [OutputConstructor]
        private SourceMongodbV2Configuration(
            Outputs.SourceMongodbV2ConfigurationDatabaseConfig databaseConfig,

            int? discoverSampleSize,

            int? initialWaitingSeconds,

            int? queueSize)
        {
            DatabaseConfig = databaseConfig;
            DiscoverSampleSize = discoverSampleSize;
            InitialWaitingSeconds = initialWaitingSeconds;
            QueueSize = queueSize;
        }
    }
}
