// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourcePostgresConfigurationReplicationMethodReadChangesUsingWriteAheadLogCdc
    {
        /// <summary>
        /// Parsed as JSON.
        /// </summary>
        public readonly string? AdditionalProperties;
        /// <summary>
        /// Specifies a query that the connector executes on the source database when the connector sends a heartbeat message. Please see the \n\nsetup guide\n\n for how and when to configure this setting. Default: ""
        /// </summary>
        public readonly string? HeartbeatActionQuery;
        /// <summary>
        /// The amount of time the connector will wait when it launches to determine if there is new data to sync or not. Defaults to 1200 seconds. Valid range: 120 seconds to 2400 seconds. Read about \n\ninitial waiting time\n\n. Default: 1200
        /// </summary>
        public readonly int? InitialWaitingSeconds;
        /// <summary>
        /// Determines when Airbyte should flush the LSN of processed WAL logs in the source database. `After loading Data in the destination` is default. If `While reading Data` is selected, in case of a downstream failure (while loading data into the destination), next sync would result in a full sync. must be one of ["While reading Data", "After loading Data in the destination"]; Default: "After loading Data in the destination"
        /// </summary>
        public readonly string? LsnCommitBehaviour;
        /// <summary>
        /// A logical decoding plugin installed on the PostgreSQL server. must be one of ["pgoutput"]; Default: "pgoutput"
        /// </summary>
        public readonly string? Plugin;
        /// <summary>
        /// A Postgres publication used for consuming changes. Read about \n\npublications and replication identities\n\n.
        /// </summary>
        public readonly string Publication;
        /// <summary>
        /// The size of the internal queue. This may interfere with memory consumption and efficiency of the connector, please be careful. Default: 10000
        /// </summary>
        public readonly int? QueueSize;
        /// <summary>
        /// A plugin logical replication slot. Read about \n\nreplication slots\n\n.
        /// </summary>
        public readonly string ReplicationSlot;

        [OutputConstructor]
        private SourcePostgresConfigurationReplicationMethodReadChangesUsingWriteAheadLogCdc(
            string? additionalProperties,

            string? heartbeatActionQuery,

            int? initialWaitingSeconds,

            string? lsnCommitBehaviour,

            string? plugin,

            string publication,

            int? queueSize,

            string replicationSlot)
        {
            AdditionalProperties = additionalProperties;
            HeartbeatActionQuery = heartbeatActionQuery;
            InitialWaitingSeconds = initialWaitingSeconds;
            LsnCommitBehaviour = lsnCommitBehaviour;
            Plugin = plugin;
            Publication = publication;
            QueueSize = queueSize;
            ReplicationSlot = replicationSlot;
        }
    }
}
