// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceMysqlConfigurationReplicationMethod
    {
        /// <summary>
        /// \n\nRecommended\n\n - Incrementally reads new inserts, updates, and deletes using the MySQL \n\nbinary log\n\n. This must be enabled on your database.
        /// </summary>
        public readonly Outputs.SourceMysqlConfigurationReplicationMethodReadChangesUsingBinaryLogCdc? ReadChangesUsingBinaryLogCdc;
        /// <summary>
        /// Incrementally detects new inserts and updates using the \n\ncursor column\n\n chosen when configuring a connection (e.g. created*at, updated*at).
        /// </summary>
        public readonly Outputs.SourceMysqlConfigurationReplicationMethodScanChangesWithUserDefinedCursor? ScanChangesWithUserDefinedCursor;

        [OutputConstructor]
        private SourceMysqlConfigurationReplicationMethod(
            Outputs.SourceMysqlConfigurationReplicationMethodReadChangesUsingBinaryLogCdc? readChangesUsingBinaryLogCdc,

            Outputs.SourceMysqlConfigurationReplicationMethodScanChangesWithUserDefinedCursor? scanChangesWithUserDefinedCursor)
        {
            ReadChangesUsingBinaryLogCdc = readChangesUsingBinaryLogCdc;
            ScanChangesWithUserDefinedCursor = scanChangesWithUserDefinedCursor;
        }
    }
}
