// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceGoogleWorkspaceAdminReportsConfiguration
    {
        /// <summary>
        /// The contents of the JSON service account key. See the \n\ndocs\n\n for more information on how to generate this key.
        /// </summary>
        public readonly string CredentialsJson;
        /// <summary>
        /// The email of the user, which has permissions to access the Google Workspace Admin APIs.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// Sets the range of time shown in the report. Reports API allows from up to 180 days ago.
        /// </summary>
        public readonly int? Lookback;

        [OutputConstructor]
        private SourceGoogleWorkspaceAdminReportsConfiguration(
            string credentialsJson,

            string email,

            int? lookback)
        {
            CredentialsJson = credentialsJson;
            Email = email;
            Lookback = lookback;
        }
    }
}
