// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceMicrosoftSharepointConfiguration
    {
        /// <summary>
        /// Credentials for connecting to the One Drive API
        /// </summary>
        public readonly Outputs.SourceMicrosoftSharepointConfigurationCredentials Credentials;
        /// <summary>
        /// Path to folder of the Microsoft SharePoint drive where the file(s) exist.
        /// </summary>
        public readonly string FolderPath;
        /// <summary>
        /// UTC date and time in the format 2017-01-25T00:00:00.000000Z. Any file modified before this date will not be replicated.
        /// </summary>
        public readonly string? StartDate;
        /// <summary>
        /// Each instance of this configuration defines a \n\nstream\n\n. Use this to define which files belong in the stream, their format, and how they should be parsed and validated. When sending data to warehouse destination such as Snowflake or BigQuery, each stream is a separate table.
        /// </summary>
        public readonly ImmutableArray<Outputs.SourceMicrosoftSharepointConfigurationStream> Streams;

        [OutputConstructor]
        private SourceMicrosoftSharepointConfiguration(
            Outputs.SourceMicrosoftSharepointConfigurationCredentials credentials,

            string folderPath,

            string? startDate,

            ImmutableArray<Outputs.SourceMicrosoftSharepointConfigurationStream> streams)
        {
            Credentials = credentials;
            FolderPath = folderPath;
            StartDate = startDate;
            Streams = streams;
        }
    }
}
