// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceMysqlConfigurationReplicationMethodReadChangesUsingBinaryLogCdc
    {
        /// <summary>
        /// The amount of time the connector will wait when it launches to determine if there is new data to sync or not. Defaults to 300 seconds. Valid range: 120 seconds to 1200 seconds. Read about \n\ninitial waiting time\n\n. Default: 300
        /// </summary>
        public readonly int? InitialWaitingSeconds;
        /// <summary>
        /// Enter the configured MySQL server timezone. This should only be done if the configured timezone in your MySQL instance does not conform to IANNA standard.
        /// </summary>
        public readonly string? ServerTimeZone;

        [OutputConstructor]
        private SourceMysqlConfigurationReplicationMethodReadChangesUsingBinaryLogCdc(
            int? initialWaitingSeconds,

            string? serverTimeZone)
        {
            InitialWaitingSeconds = initialWaitingSeconds;
            ServerTimeZone = serverTimeZone;
        }
    }
}
