// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceSnapchatMarketingConfiguration
    {
        /// <summary>
        /// The Client ID of your Snapchat developer application.
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// The Client Secret of your Snapchat developer application.
        /// </summary>
        public readonly string ClientSecret;
        /// <summary>
        /// Date in the format 2017-01-25. Any data after this date will not be replicated.
        /// </summary>
        public readonly string? EndDate;
        /// <summary>
        /// Refresh Token to renew the expired Access Token.
        /// </summary>
        public readonly string RefreshToken;
        /// <summary>
        /// Date in the format 2022-01-01. Any data before this date will not be replicated. Default: "2022-01-01"
        /// </summary>
        public readonly string? StartDate;

        [OutputConstructor]
        private SourceSnapchatMarketingConfiguration(
            string clientId,

            string clientSecret,

            string? endDate,

            string refreshToken,

            string? startDate)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            EndDate = endDate;
            RefreshToken = refreshToken;
            StartDate = startDate;
        }
    }
}
