// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceGoogleSearchConsoleConfigurationAuthorizationServiceAccountKeyAuthentication
    {
        /// <summary>
        /// The email of the user which has permissions to access the Google Workspace Admin APIs.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// The JSON key of the service account to use for authorization. Read more \n\nhere\n\n.
        /// </summary>
        public readonly string ServiceAccountInfo;

        [OutputConstructor]
        private SourceGoogleSearchConsoleConfigurationAuthorizationServiceAccountKeyAuthentication(
            string email,

            string serviceAccountInfo)
        {
            Email = email;
            ServiceAccountInfo = serviceAccountInfo;
        }
    }
}
