// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceZendeskSupportConfigurationCredentialsOAuth20
    {
        /// <summary>
        /// The OAuth access token. See the \n\nZendesk docs\n\n for more information on generating this token.
        /// </summary>
        public readonly string AccessToken;
        /// <summary>
        /// Parsed as JSON.
        /// </summary>
        public readonly string? AdditionalProperties;
        /// <summary>
        /// The OAuth client's ID. See \n\nthis guide\n\n for more information.
        /// </summary>
        public readonly string? ClientId;
        /// <summary>
        /// The OAuth client secret. See \n\nthis guide\n\n for more information.
        /// </summary>
        public readonly string? ClientSecret;

        [OutputConstructor]
        private SourceZendeskSupportConfigurationCredentialsOAuth20(
            string accessToken,

            string? additionalProperties,

            string? clientId,

            string? clientSecret)
        {
            AccessToken = accessToken;
            AdditionalProperties = additionalProperties;
            ClientId = clientId;
            ClientSecret = clientSecret;
        }
    }
}
