// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceFaunaConfigurationCollection
    {
        /// <summary>
        /// \n\nThis only applies to incremental syncs.\n\n \n\n
        /// Enabling deletion mode informs your destination of deleted documents.\n\n
        /// Disabled - Leave this feature disabled, and ignore deleted documents.\n\n
        /// Enabled - Enables this feature. When a document is deleted, the connector exports a record with a "deleted at" column containing the time that the document was deleted.
        /// </summary>
        public readonly Outputs.SourceFaunaConfigurationCollectionDeletions Deletions;
        /// <summary>
        /// The page size used when reading documents from the database. The larger the page size, the faster the connector processes documents. However, if a page is too large, the connector may fail. \n\n
        /// Choose your page size based on how large the documents are. \n\n
        /// See \n\nthe docs\n\n.
        /// Default: 64
        /// </summary>
        public readonly int? PageSize;

        [OutputConstructor]
        private SourceFaunaConfigurationCollection(
            Outputs.SourceFaunaConfigurationCollectionDeletions deletions,

            int? pageSize)
        {
            Deletions = deletions;
            PageSize = pageSize;
        }
    }
}
