// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceExchangeRatesConfiguration
    {
        /// <summary>
        /// Your API Key. See \n\nhere\n\n. The key is case sensitive.
        /// </summary>
        public readonly string AccessKey;
        /// <summary>
        /// ISO reference currency. See \n\nhere\n\n. Free plan doesn't support Source Currency Switching, default base currency is EUR
        /// </summary>
        public readonly string? Base;
        /// <summary>
        /// Ignore weekends? (Exchanges don't run on weekends). Default: true
        /// </summary>
        public readonly bool? IgnoreWeekends;
        /// <summary>
        /// Start getting data from that date.
        /// </summary>
        public readonly string StartDate;

        [OutputConstructor]
        private SourceExchangeRatesConfiguration(
            string accessKey,

            string? @base,

            bool? ignoreWeekends,

            string startDate)
        {
            AccessKey = accessKey;
            Base = @base;
            IgnoreWeekends = ignoreWeekends;
            StartDate = startDate;
        }
    }
}
