// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceAmazonAdsConfiguration
    {
        /// <summary>
        /// The client ID of your Amazon Ads developer application. See the \n\ndocs\n\n for more information.
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// The client secret of your Amazon Ads developer application. See the \n\ndocs\n\n for more information.
        /// </summary>
        public readonly string ClientSecret;
        /// <summary>
        /// The amount of days to go back in time to get the updated data from Amazon Ads. Default: 3
        /// </summary>
        public readonly int? LookBackWindow;
        /// <summary>
        /// Marketplace IDs you want to fetch data for. Note: If Profile IDs are also selected, profiles will be selected if they match the Profile ID OR the Marketplace ID.
        /// </summary>
        public readonly ImmutableArray<string> MarketplaceIds;
        /// <summary>
        /// Profile IDs you want to fetch data for. See \n\ndocs\n\n for more details. Note: If Marketplace IDs are also selected, profiles will be selected if they match the Profile ID OR the Marketplace ID.
        /// </summary>
        public readonly ImmutableArray<int> Profiles;
        /// <summary>
        /// Amazon Ads refresh token. See the \n\ndocs\n\n for more information on how to obtain this token.
        /// </summary>
        public readonly string RefreshToken;
        /// <summary>
        /// Region to pull data from (EU/NA/FE). See \n\ndocs\n\n for more details. must be one of ["NA", "EU", "FE"]; Default: "NA"
        /// </summary>
        public readonly string? Region;
        /// <summary>
        /// Optional configuration which accepts an array of string of record types. Leave blank for default behaviour to pull all report types. Use this config option only if you want to pull specific report type(s). See \n\ndocs\n\n for more details
        /// </summary>
        public readonly ImmutableArray<string> ReportRecordTypes;
        /// <summary>
        /// The Start date for collecting reports, should not be more than 60 days in the past. In YYYY-MM-DD format
        /// </summary>
        public readonly string? StartDate;
        /// <summary>
        /// Reflects the state of the Display, Product, and Brand Campaign streams as enabled, paused, or archived. If you do not populate this field, it will be ignored completely.
        /// </summary>
        public readonly ImmutableArray<string> StateFilters;

        [OutputConstructor]
        private SourceAmazonAdsConfiguration(
            string clientId,

            string clientSecret,

            int? lookBackWindow,

            ImmutableArray<string> marketplaceIds,

            ImmutableArray<int> profiles,

            string refreshToken,

            string? region,

            ImmutableArray<string> reportRecordTypes,

            string? startDate,

            ImmutableArray<string> stateFilters)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            LookBackWindow = lookBackWindow;
            MarketplaceIds = marketplaceIds;
            Profiles = profiles;
            RefreshToken = refreshToken;
            Region = region;
            ReportRecordTypes = reportRecordTypes;
            StartDate = startDate;
            StateFilters = stateFilters;
        }
    }
}
