// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceFireboltConfiguration
    {
        /// <summary>
        /// Firebolt account to login.
        /// </summary>
        public readonly string? Account;
        /// <summary>
        /// The database to connect to.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Engine name or url to connect to.
        /// </summary>
        public readonly string? Engine;
        /// <summary>
        /// The host name of your Firebolt database.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// Firebolt password.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// Firebolt email address you use to login.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private SourceFireboltConfiguration(
            string? account,

            string database,

            string? engine,

            string? host,

            string password,

            string username)
        {
            Account = account;
            Database = database;
            Engine = engine;
            Host = host;
            Password = password;
            Username = username;
        }
    }
}
