// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SourceMicrosoftSharepoint DataSource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := airbyte.LookupSourceMicrosoftSharepoint(ctx, &airbyte.LookupSourceMicrosoftSharepointArgs{
//				SourceId: "...my_source_id...",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSourceMicrosoftSharepoint(ctx *pulumi.Context, args *LookupSourceMicrosoftSharepointArgs, opts ...pulumi.InvokeOption) (*LookupSourceMicrosoftSharepointResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceMicrosoftSharepointResult
	err := ctx.Invoke("airbyte:index/getSourceMicrosoftSharepoint:getSourceMicrosoftSharepoint", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceMicrosoftSharepoint.
type LookupSourceMicrosoftSharepointArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceMicrosoftSharepoint.
type LookupSourceMicrosoftSharepointResult struct {
	// The values required to configure the source. Parsed as JSON.
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceMicrosoftSharepointOutput(ctx *pulumi.Context, args LookupSourceMicrosoftSharepointOutputArgs, opts ...pulumi.InvokeOption) LookupSourceMicrosoftSharepointResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceMicrosoftSharepointResult, error) {
			args := v.(LookupSourceMicrosoftSharepointArgs)
			r, err := LookupSourceMicrosoftSharepoint(ctx, &args, opts...)
			var s LookupSourceMicrosoftSharepointResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceMicrosoftSharepointResultOutput)
}

// A collection of arguments for invoking getSourceMicrosoftSharepoint.
type LookupSourceMicrosoftSharepointOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceMicrosoftSharepointOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceMicrosoftSharepointArgs)(nil)).Elem()
}

// A collection of values returned by getSourceMicrosoftSharepoint.
type LookupSourceMicrosoftSharepointResultOutput struct{ *pulumi.OutputState }

func (LookupSourceMicrosoftSharepointResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceMicrosoftSharepointResult)(nil)).Elem()
}

func (o LookupSourceMicrosoftSharepointResultOutput) ToLookupSourceMicrosoftSharepointResultOutput() LookupSourceMicrosoftSharepointResultOutput {
	return o
}

func (o LookupSourceMicrosoftSharepointResultOutput) ToLookupSourceMicrosoftSharepointResultOutputWithContext(ctx context.Context) LookupSourceMicrosoftSharepointResultOutput {
	return o
}

// The values required to configure the source. Parsed as JSON.
func (o LookupSourceMicrosoftSharepointResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceMicrosoftSharepointResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceMicrosoftSharepointResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceMicrosoftSharepointResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceMicrosoftSharepointResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceMicrosoftSharepointResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceMicrosoftSharepointResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceMicrosoftSharepointResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceMicrosoftSharepointResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceMicrosoftSharepointResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceMicrosoftSharepointResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceMicrosoftSharepointResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceMicrosoftSharepointResultOutput{})
}
