// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SourceSenseforce DataSource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := airbyte.LookupSourceSenseforce(ctx, &airbyte.LookupSourceSenseforceArgs{
//				SourceId: "...my_source_id...",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSourceSenseforce(ctx *pulumi.Context, args *LookupSourceSenseforceArgs, opts ...pulumi.InvokeOption) (*LookupSourceSenseforceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceSenseforceResult
	err := ctx.Invoke("airbyte:index/getSourceSenseforce:getSourceSenseforce", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceSenseforce.
type LookupSourceSenseforceArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceSenseforce.
type LookupSourceSenseforceResult struct {
	// The values required to configure the source. Parsed as JSON.
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceSenseforceOutput(ctx *pulumi.Context, args LookupSourceSenseforceOutputArgs, opts ...pulumi.InvokeOption) LookupSourceSenseforceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceSenseforceResult, error) {
			args := v.(LookupSourceSenseforceArgs)
			r, err := LookupSourceSenseforce(ctx, &args, opts...)
			var s LookupSourceSenseforceResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceSenseforceResultOutput)
}

// A collection of arguments for invoking getSourceSenseforce.
type LookupSourceSenseforceOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceSenseforceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceSenseforceArgs)(nil)).Elem()
}

// A collection of values returned by getSourceSenseforce.
type LookupSourceSenseforceResultOutput struct{ *pulumi.OutputState }

func (LookupSourceSenseforceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceSenseforceResult)(nil)).Elem()
}

func (o LookupSourceSenseforceResultOutput) ToLookupSourceSenseforceResultOutput() LookupSourceSenseforceResultOutput {
	return o
}

func (o LookupSourceSenseforceResultOutput) ToLookupSourceSenseforceResultOutputWithContext(ctx context.Context) LookupSourceSenseforceResultOutput {
	return o
}

// The values required to configure the source. Parsed as JSON.
func (o LookupSourceSenseforceResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSenseforceResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceSenseforceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSenseforceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceSenseforceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSenseforceResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceSenseforceResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSenseforceResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceSenseforceResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSenseforceResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceSenseforceResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSenseforceResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceSenseforceResultOutput{})
}
