// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SourceGoogleWorkspaceAdminReports DataSource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := airbyte.LookupSourceGoogleWorkspaceAdminReports(ctx, &airbyte.LookupSourceGoogleWorkspaceAdminReportsArgs{
//				SourceId: "...my_source_id...",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSourceGoogleWorkspaceAdminReports(ctx *pulumi.Context, args *LookupSourceGoogleWorkspaceAdminReportsArgs, opts ...pulumi.InvokeOption) (*LookupSourceGoogleWorkspaceAdminReportsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceGoogleWorkspaceAdminReportsResult
	err := ctx.Invoke("airbyte:index/getSourceGoogleWorkspaceAdminReports:getSourceGoogleWorkspaceAdminReports", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceGoogleWorkspaceAdminReports.
type LookupSourceGoogleWorkspaceAdminReportsArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceGoogleWorkspaceAdminReports.
type LookupSourceGoogleWorkspaceAdminReportsResult struct {
	// The values required to configure the source. Parsed as JSON.
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceGoogleWorkspaceAdminReportsOutput(ctx *pulumi.Context, args LookupSourceGoogleWorkspaceAdminReportsOutputArgs, opts ...pulumi.InvokeOption) LookupSourceGoogleWorkspaceAdminReportsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceGoogleWorkspaceAdminReportsResult, error) {
			args := v.(LookupSourceGoogleWorkspaceAdminReportsArgs)
			r, err := LookupSourceGoogleWorkspaceAdminReports(ctx, &args, opts...)
			var s LookupSourceGoogleWorkspaceAdminReportsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceGoogleWorkspaceAdminReportsResultOutput)
}

// A collection of arguments for invoking getSourceGoogleWorkspaceAdminReports.
type LookupSourceGoogleWorkspaceAdminReportsOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceGoogleWorkspaceAdminReportsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceGoogleWorkspaceAdminReportsArgs)(nil)).Elem()
}

// A collection of values returned by getSourceGoogleWorkspaceAdminReports.
type LookupSourceGoogleWorkspaceAdminReportsResultOutput struct{ *pulumi.OutputState }

func (LookupSourceGoogleWorkspaceAdminReportsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceGoogleWorkspaceAdminReportsResult)(nil)).Elem()
}

func (o LookupSourceGoogleWorkspaceAdminReportsResultOutput) ToLookupSourceGoogleWorkspaceAdminReportsResultOutput() LookupSourceGoogleWorkspaceAdminReportsResultOutput {
	return o
}

func (o LookupSourceGoogleWorkspaceAdminReportsResultOutput) ToLookupSourceGoogleWorkspaceAdminReportsResultOutputWithContext(ctx context.Context) LookupSourceGoogleWorkspaceAdminReportsResultOutput {
	return o
}

// The values required to configure the source. Parsed as JSON.
func (o LookupSourceGoogleWorkspaceAdminReportsResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWorkspaceAdminReportsResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceGoogleWorkspaceAdminReportsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWorkspaceAdminReportsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceGoogleWorkspaceAdminReportsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWorkspaceAdminReportsResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceGoogleWorkspaceAdminReportsResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWorkspaceAdminReportsResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceGoogleWorkspaceAdminReportsResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWorkspaceAdminReportsResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceGoogleWorkspaceAdminReportsResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWorkspaceAdminReportsResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceGoogleWorkspaceAdminReportsResultOutput{})
}
