// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SourceGitlab DataSource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := airbyte.LookupSourceGitlab(ctx, &airbyte.LookupSourceGitlabArgs{
//				SourceId: "...my_source_id...",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSourceGitlab(ctx *pulumi.Context, args *LookupSourceGitlabArgs, opts ...pulumi.InvokeOption) (*LookupSourceGitlabResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceGitlabResult
	err := ctx.Invoke("airbyte:index/getSourceGitlab:getSourceGitlab", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceGitlab.
type LookupSourceGitlabArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceGitlab.
type LookupSourceGitlabResult struct {
	// The values required to configure the source. Parsed as JSON.
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceGitlabOutput(ctx *pulumi.Context, args LookupSourceGitlabOutputArgs, opts ...pulumi.InvokeOption) LookupSourceGitlabResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceGitlabResult, error) {
			args := v.(LookupSourceGitlabArgs)
			r, err := LookupSourceGitlab(ctx, &args, opts...)
			var s LookupSourceGitlabResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceGitlabResultOutput)
}

// A collection of arguments for invoking getSourceGitlab.
type LookupSourceGitlabOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceGitlabOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceGitlabArgs)(nil)).Elem()
}

// A collection of values returned by getSourceGitlab.
type LookupSourceGitlabResultOutput struct{ *pulumi.OutputState }

func (LookupSourceGitlabResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceGitlabResult)(nil)).Elem()
}

func (o LookupSourceGitlabResultOutput) ToLookupSourceGitlabResultOutput() LookupSourceGitlabResultOutput {
	return o
}

func (o LookupSourceGitlabResultOutput) ToLookupSourceGitlabResultOutputWithContext(ctx context.Context) LookupSourceGitlabResultOutput {
	return o
}

// The values required to configure the source. Parsed as JSON.
func (o LookupSourceGitlabResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGitlabResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceGitlabResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGitlabResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceGitlabResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGitlabResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceGitlabResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGitlabResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceGitlabResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGitlabResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceGitlabResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGitlabResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceGitlabResultOutput{})
}
