// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SourceRecruitee DataSource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-airbyte/sdk/go/airbyte"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := airbyte.LookupSourceRecruitee(ctx, &airbyte.LookupSourceRecruiteeArgs{
//				SourceId: "...my_source_id...",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSourceRecruitee(ctx *pulumi.Context, args *LookupSourceRecruiteeArgs, opts ...pulumi.InvokeOption) (*LookupSourceRecruiteeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceRecruiteeResult
	err := ctx.Invoke("airbyte:index/getSourceRecruitee:getSourceRecruitee", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceRecruitee.
type LookupSourceRecruiteeArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceRecruitee.
type LookupSourceRecruiteeResult struct {
	// The values required to configure the source. Parsed as JSON.
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceRecruiteeOutput(ctx *pulumi.Context, args LookupSourceRecruiteeOutputArgs, opts ...pulumi.InvokeOption) LookupSourceRecruiteeResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceRecruiteeResult, error) {
			args := v.(LookupSourceRecruiteeArgs)
			r, err := LookupSourceRecruitee(ctx, &args, opts...)
			var s LookupSourceRecruiteeResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceRecruiteeResultOutput)
}

// A collection of arguments for invoking getSourceRecruitee.
type LookupSourceRecruiteeOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceRecruiteeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceRecruiteeArgs)(nil)).Elem()
}

// A collection of values returned by getSourceRecruitee.
type LookupSourceRecruiteeResultOutput struct{ *pulumi.OutputState }

func (LookupSourceRecruiteeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceRecruiteeResult)(nil)).Elem()
}

func (o LookupSourceRecruiteeResultOutput) ToLookupSourceRecruiteeResultOutput() LookupSourceRecruiteeResultOutput {
	return o
}

func (o LookupSourceRecruiteeResultOutput) ToLookupSourceRecruiteeResultOutputWithContext(ctx context.Context) LookupSourceRecruiteeResultOutput {
	return o
}

// The values required to configure the source. Parsed as JSON.
func (o LookupSourceRecruiteeResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceRecruiteeResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceRecruiteeResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceRecruiteeResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceRecruiteeResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceRecruiteeResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceRecruiteeResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceRecruiteeResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceRecruiteeResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceRecruiteeResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceRecruiteeResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceRecruiteeResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceRecruiteeResultOutput{})
}
