// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationKinesisConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Generate the AWS Access Key for current user.
        /// </summary>
        [Input("accessKey", required: true)]
        public Input<string> AccessKey { get; set; } = null!;

        /// <summary>
        /// Buffer size for storing kinesis records before being batch streamed. Default: 100
        /// </summary>
        [Input("bufferSize")]
        public Input<int>? BufferSize { get; set; }

        /// <summary>
        /// AWS Kinesis endpoint.
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        /// <summary>
        /// The AWS Private Key - a string of numbers and letters that are unique for each account, also known as a "recovery phrase".
        /// </summary>
        [Input("privateKey", required: true)]
        public Input<string> PrivateKey { get; set; } = null!;

        /// <summary>
        /// AWS region. Your account determines the Regions that are available to you.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// Number of shards to which the data should be streamed. Default: 5
        /// </summary>
        [Input("shardCount")]
        public Input<int>? ShardCount { get; set; }

        public DestinationKinesisConfigurationGetArgs()
        {
        }
        public static new DestinationKinesisConfigurationGetArgs Empty => new DestinationKinesisConfigurationGetArgs();
    }
}
