// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationS3ConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKeyId")]
        private Input<string>? _accessKeyId;

        /// <summary>
        /// The access key ID to access the S3 bucket. Airbyte requires Read and Write permissions to the given bucket. Read more \n\nhere\n\n.
        /// </summary>
        public Input<string>? AccessKeyId
        {
            get => _accessKeyId;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessKeyId = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The pattern allows you to set the file-name format for the S3 staging file(s)
        /// </summary>
        [Input("fileNamePattern")]
        public Input<string>? FileNamePattern { get; set; }

        /// <summary>
        /// Format of the data output. See \n\nhere\n\n for more details
        /// </summary>
        [Input("format", required: true)]
        public Input<Inputs.DestinationS3ConfigurationFormatArgs> Format { get; set; } = null!;

        /// <summary>
        /// The name of the S3 bucket. Read more \n\nhere\n\n.
        /// </summary>
        [Input("s3BucketName", required: true)]
        public Input<string> S3BucketName { get; set; } = null!;

        /// <summary>
        /// Directory under the S3 bucket where data will be written. Read more \n\nhere\n\n
        /// </summary>
        [Input("s3BucketPath", required: true)]
        public Input<string> S3BucketPath { get; set; } = null!;

        /// <summary>
        /// The region of the S3 bucket. See \n\nhere\n\n for all region codes. must be one of ["", "af-south-1", "ap-east-1", "ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-south-1", "ap-south-2", "ap-southeast-1", "ap-southeast-2", "ap-southeast-3", "ap-southeast-4", "ca-central-1", "ca-west-1", "cn-north-1", "cn-northwest-1", "eu-central-1", "eu-central-2", "eu-north-1", "eu-south-1", "eu-south-2", "eu-west-1", "eu-west-2", "eu-west-3", "il-central-1", "me-central-1", "me-south-1", "sa-east-1", "us-east-1", "us-east-2", "us-gov-east-1", "us-gov-west-1", "us-west-1", "us-west-2"]; Default: ""
        /// </summary>
        [Input("s3BucketRegion")]
        public Input<string>? S3BucketRegion { get; set; }

        /// <summary>
        /// Your S3 endpoint url. Read more \n\nhere\n\n. Default: ""
        /// </summary>
        [Input("s3Endpoint")]
        public Input<string>? S3Endpoint { get; set; }

        /// <summary>
        /// Format string on how data will be organized inside the S3 bucket directory. Read more \n\nhere\n\n
        /// </summary>
        [Input("s3PathFormat")]
        public Input<string>? S3PathFormat { get; set; }

        [Input("secretAccessKey")]
        private Input<string>? _secretAccessKey;

        /// <summary>
        /// The corresponding secret to the access key ID. Read more \n\nhere\n\n
        /// </summary>
        public Input<string>? SecretAccessKey
        {
            get => _secretAccessKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretAccessKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public DestinationS3ConfigurationArgs()
        {
        }
        public static new DestinationS3ConfigurationArgs Empty => new DestinationS3ConfigurationArgs();
    }
}
