// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationFireboltConfigurationLoadingMethodArgs : global::Pulumi.ResourceArgs
    {
        [Input("externalTableViaS3")]
        public Input<Inputs.DestinationFireboltConfigurationLoadingMethodExternalTableViaS3Args>? ExternalTableViaS3 { get; set; }

        [Input("sqlInserts")]
        public Input<Inputs.DestinationFireboltConfigurationLoadingMethodSqlInsertsArgs>? SqlInserts { get; set; }

        public DestinationFireboltConfigurationLoadingMethodArgs()
        {
        }
        public static new DestinationFireboltConfigurationLoadingMethodArgs Empty => new DestinationFireboltConfigurationLoadingMethodArgs();
    }
}
