// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGoogleSheetsConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Credentials for connecting to the Google Sheets API
        /// </summary>
        [Input("credentials", required: true)]
        public Input<Inputs.SourceGoogleSheetsConfigurationCredentialsGetArgs> Credentials { get; set; } = null!;

        /// <summary>
        /// Enables the conversion of column names to a standardized, SQL-compliant format. For example, 'My Name' &gt; 'my_name'. Enable this option if your destination is SQL-based. Default: false
        /// </summary>
        [Input("namesConversion")]
        public Input<bool>? NamesConversion { get; set; }

        /// <summary>
        /// Enter the link to the Google spreadsheet you want to sync. To copy the link, click the 'Share' button in the top-right corner of the spreadsheet, then click 'Copy link'.
        /// </summary>
        [Input("spreadsheetId", required: true)]
        public Input<string> SpreadsheetId { get; set; } = null!;

        public SourceGoogleSheetsConfigurationGetArgs()
        {
        }
        public static new SourceGoogleSheetsConfigurationGetArgs Empty => new SourceGoogleSheetsConfigurationGetArgs();
    }
}
