// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGoogleDriveConfigurationCredentialsServiceAccountKeyAuthenticationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The JSON key of the service account to use for authorization. Read more \n\nhere\n\n.
        /// </summary>
        [Input("serviceAccountInfo", required: true)]
        public Input<string> ServiceAccountInfo { get; set; } = null!;

        public SourceGoogleDriveConfigurationCredentialsServiceAccountKeyAuthenticationArgs()
        {
        }
        public static new SourceGoogleDriveConfigurationCredentialsServiceAccountKeyAuthenticationArgs Empty => new SourceGoogleDriveConfigurationCredentialsServiceAccountKeyAuthenticationArgs();
    }
}
