// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGoogleDirectoryConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Google APIs use the OAuth 2.0 protocol for authentication and authorization. The Source supports \n\nWeb server application\n\n and \n\nService accounts\n\n scenarios.
        /// </summary>
        [Input("credentials")]
        public Input<Inputs.SourceGoogleDirectoryConfigurationCredentialsGetArgs>? Credentials { get; set; }

        public SourceGoogleDirectoryConfigurationGetArgs()
        {
        }
        public static new SourceGoogleDirectoryConfigurationGetArgs Empty => new SourceGoogleDirectoryConfigurationGetArgs();
    }
}
