// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourcePaypalTransactionConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Client ID of your Paypal developer application.
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// The Client Secret of your Paypal developer application.
        /// </summary>
        [Input("clientSecret", required: true)]
        public Input<string> ClientSecret { get; set; } = null!;

        /// <summary>
        /// Determines whether to use the sandbox or production environment. Default: false
        /// </summary>
        [Input("isSandbox")]
        public Input<bool>? IsSandbox { get; set; }

        [Input("refreshToken")]
        private Input<string>? _refreshToken;

        /// <summary>
        /// The key to refresh the expired access token.
        /// </summary>
        public Input<string>? RefreshToken
        {
            get => _refreshToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _refreshToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Start Date for data extraction in \n\nISO format\n\n. Date must be in range from 3 years till 12 hrs before present time.
        /// </summary>
        [Input("startDate", required: true)]
        public Input<string> StartDate { get; set; } = null!;

        /// <summary>
        /// The number of days per request. Must be a number between 1 and 31. Default: 7
        /// </summary>
        [Input("timeWindow")]
        public Input<int>? TimeWindow { get; set; }

        public SourcePaypalTransactionConfigurationArgs()
        {
        }
        public static new SourcePaypalTransactionConfigurationArgs Empty => new SourcePaypalTransactionConfigurationArgs();
    }
}
