// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceFireboltConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Firebolt account to login.
        /// </summary>
        [Input("account")]
        public Input<string>? Account { get; set; }

        /// <summary>
        /// The database to connect to.
        /// </summary>
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        /// <summary>
        /// Engine name or url to connect to.
        /// </summary>
        [Input("engine")]
        public Input<string>? Engine { get; set; }

        /// <summary>
        /// The host name of your Firebolt database.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        [Input("password", required: true)]
        private Input<string>? _password;

        /// <summary>
        /// Firebolt password.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Firebolt email address you use to login.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public SourceFireboltConfigurationArgs()
        {
        }
        public static new SourceFireboltConfigurationArgs Empty => new SourceFireboltConfigurationArgs();
    }
}
