// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceMysqlConfigurationReplicationMethodGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// \n\nRecommended\n\n - Incrementally reads new inserts, updates, and deletes using the MySQL \n\nbinary log\n\n. This must be enabled on your database.
        /// </summary>
        [Input("readChangesUsingBinaryLogCdc")]
        public Input<Inputs.SourceMysqlConfigurationReplicationMethodReadChangesUsingBinaryLogCdcGetArgs>? ReadChangesUsingBinaryLogCdc { get; set; }

        /// <summary>
        /// Incrementally detects new inserts and updates using the \n\ncursor column\n\n chosen when configuring a connection (e.g. created*at, updated*at).
        /// </summary>
        [Input("scanChangesWithUserDefinedCursor")]
        public Input<Inputs.SourceMysqlConfigurationReplicationMethodScanChangesWithUserDefinedCursorGetArgs>? ScanChangesWithUserDefinedCursor { get; set; }

        public SourceMysqlConfigurationReplicationMethodGetArgs()
        {
        }
        public static new SourceMysqlConfigurationReplicationMethodGetArgs Empty => new SourceMysqlConfigurationReplicationMethodGetArgs();
    }
}
