// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGoogleAnalyticsDataApiConfigurationCredentialsServiceAccountKeyAuthenticationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The JSON key linked to the service account used for authorization. For steps on obtaining this key, refer to \n\nthe setup guide\n\n.
        /// </summary>
        [Input("credentialsJson", required: true)]
        public Input<string> CredentialsJson { get; set; } = null!;

        public SourceGoogleAnalyticsDataApiConfigurationCredentialsServiceAccountKeyAuthenticationGetArgs()
        {
        }
        public static new SourceGoogleAnalyticsDataApiConfigurationCredentialsServiceAccountKeyAuthenticationGetArgs Empty => new SourceGoogleAnalyticsDataApiConfigurationCredentialsServiceAccountKeyAuthenticationGetArgs();
    }
}
