// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * DestinationRedis DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const myDestinationRedis = airbyte.getDestinationRedis({
 *     destinationId: "...my_destination_id...",
 * });
 * ```
 */
export function getDestinationRedis(args: GetDestinationRedisArgs, opts?: pulumi.InvokeOptions): Promise<GetDestinationRedisResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getDestinationRedis:getDestinationRedis", {
        "destinationId": args.destinationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDestinationRedis.
 */
export interface GetDestinationRedisArgs {
    destinationId: string;
}

/**
 * A collection of values returned by getDestinationRedis.
 */
export interface GetDestinationRedisResult {
    /**
     * The values required to configure the destination. Parsed as JSON.
     */
    readonly configuration: string;
    readonly destinationId: string;
    readonly destinationType: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly workspaceId: string;
}
/**
 * DestinationRedis DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const myDestinationRedis = airbyte.getDestinationRedis({
 *     destinationId: "...my_destination_id...",
 * });
 * ```
 */
export function getDestinationRedisOutput(args: GetDestinationRedisOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDestinationRedisResult> {
    return pulumi.output(args).apply((a: any) => getDestinationRedis(a, opts))
}

/**
 * A collection of arguments for invoking getDestinationRedis.
 */
export interface GetDestinationRedisOutputArgs {
    destinationId: pulumi.Input<string>;
}
