// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * DestinationPinecone DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const myDestinationPinecone = airbyte.getDestinationPinecone({
 *     destinationId: "...my_destination_id...",
 * });
 * ```
 */
export function getDestinationPinecone(args: GetDestinationPineconeArgs, opts?: pulumi.InvokeOptions): Promise<GetDestinationPineconeResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getDestinationPinecone:getDestinationPinecone", {
        "destinationId": args.destinationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDestinationPinecone.
 */
export interface GetDestinationPineconeArgs {
    destinationId: string;
}

/**
 * A collection of values returned by getDestinationPinecone.
 */
export interface GetDestinationPineconeResult {
    /**
     * The values required to configure the destination. Parsed as JSON.
     */
    readonly configuration: string;
    readonly destinationId: string;
    readonly destinationType: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly workspaceId: string;
}
/**
 * DestinationPinecone DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const myDestinationPinecone = airbyte.getDestinationPinecone({
 *     destinationId: "...my_destination_id...",
 * });
 * ```
 */
export function getDestinationPineconeOutput(args: GetDestinationPineconeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDestinationPineconeResult> {
    return pulumi.output(args).apply((a: any) => getDestinationPinecone(a, opts))
}

/**
 * A collection of arguments for invoking getDestinationPinecone.
 */
export interface GetDestinationPineconeOutputArgs {
    destinationId: pulumi.Input<string>;
}
