// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * DestinationAzureBlobStorage DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const myDestinationAzureblobstorage = airbyte.getDestinationAzureBlobStorage({
 *     destinationId: "...my_destination_id...",
 * });
 * ```
 */
export function getDestinationAzureBlobStorage(args: GetDestinationAzureBlobStorageArgs, opts?: pulumi.InvokeOptions): Promise<GetDestinationAzureBlobStorageResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getDestinationAzureBlobStorage:getDestinationAzureBlobStorage", {
        "destinationId": args.destinationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDestinationAzureBlobStorage.
 */
export interface GetDestinationAzureBlobStorageArgs {
    destinationId: string;
}

/**
 * A collection of values returned by getDestinationAzureBlobStorage.
 */
export interface GetDestinationAzureBlobStorageResult {
    /**
     * The values required to configure the destination. Parsed as JSON.
     */
    readonly configuration: string;
    readonly destinationId: string;
    readonly destinationType: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly workspaceId: string;
}
/**
 * DestinationAzureBlobStorage DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const myDestinationAzureblobstorage = airbyte.getDestinationAzureBlobStorage({
 *     destinationId: "...my_destination_id...",
 * });
 * ```
 */
export function getDestinationAzureBlobStorageOutput(args: GetDestinationAzureBlobStorageOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDestinationAzureBlobStorageResult> {
    return pulumi.output(args).apply((a: any) => getDestinationAzureBlobStorage(a, opts))
}

/**
 * A collection of arguments for invoking getDestinationAzureBlobStorage.
 */
export interface GetDestinationAzureBlobStorageOutputArgs {
    destinationId: pulumi.Input<string>;
}
