// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceQuickbooks DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceQuickbooks = airbyte.getSourceQuickbooks({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceQuickbooks(args: GetSourceQuickbooksArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceQuickbooksResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceQuickbooks:getSourceQuickbooks", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceQuickbooks.
 */
export interface GetSourceQuickbooksArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceQuickbooks.
 */
export interface GetSourceQuickbooksResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceQuickbooks DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceQuickbooks = airbyte.getSourceQuickbooks({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceQuickbooksOutput(args: GetSourceQuickbooksOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceQuickbooksResult> {
    return pulumi.output(args).apply((a: any) => getSourceQuickbooks(a, opts))
}

/**
 * A collection of arguments for invoking getSourceQuickbooks.
 */
export interface GetSourceQuickbooksOutputArgs {
    sourceId: pulumi.Input<string>;
}
