// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceCart DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceCart = airbyte.getSourceCart({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceCart(args: GetSourceCartArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCartResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCart:getSourceCart", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceCart.
 */
export interface GetSourceCartArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCart.
 */
export interface GetSourceCartResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceCart DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceCart = airbyte.getSourceCart({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceCartOutput(args: GetSourceCartOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceCartResult> {
    return pulumi.output(args).apply((a: any) => getSourceCart(a, opts))
}

/**
 * A collection of arguments for invoking getSourceCart.
 */
export interface GetSourceCartOutputArgs {
    sourceId: pulumi.Input<string>;
}
