// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceCoda DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceCoda = airbyte.getSourceCoda({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceCoda(args: GetSourceCodaArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCodaResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCoda:getSourceCoda", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceCoda.
 */
export interface GetSourceCodaArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCoda.
 */
export interface GetSourceCodaResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceCoda DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceCoda = airbyte.getSourceCoda({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceCodaOutput(args: GetSourceCodaOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceCodaResult> {
    return pulumi.output(args).apply((a: any) => getSourceCoda(a, opts))
}

/**
 * A collection of arguments for invoking getSourceCoda.
 */
export interface GetSourceCodaOutputArgs {
    sourceId: pulumi.Input<string>;
}
