// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceAmazonAds DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceAmazonads = airbyte.getSourceAmazonAds({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceAmazonAds(args: GetSourceAmazonAdsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAmazonAdsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAmazonAds:getSourceAmazonAds", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceAmazonAds.
 */
export interface GetSourceAmazonAdsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAmazonAds.
 */
export interface GetSourceAmazonAdsResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceAmazonAds DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceAmazonads = airbyte.getSourceAmazonAds({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceAmazonAdsOutput(args: GetSourceAmazonAdsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceAmazonAdsResult> {
    return pulumi.output(args).apply((a: any) => getSourceAmazonAds(a, opts))
}

/**
 * A collection of arguments for invoking getSourceAmazonAds.
 */
export interface GetSourceAmazonAdsOutputArgs {
    sourceId: pulumi.Input<string>;
}
