// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceRss DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceRss = airbyte.getSourceRss({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceRss(args: GetSourceRssArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceRssResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceRss:getSourceRss", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceRss.
 */
export interface GetSourceRssArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceRss.
 */
export interface GetSourceRssResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceRss DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceRss = airbyte.getSourceRss({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceRssOutput(args: GetSourceRssOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceRssResult> {
    return pulumi.output(args).apply((a: any) => getSourceRss(a, opts))
}

/**
 * A collection of arguments for invoking getSourceRss.
 */
export interface GetSourceRssOutputArgs {
    sourceId: pulumi.Input<string>;
}
