// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceFile DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceFile = airbyte.getSourceFile({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceFile(args: GetSourceFileArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFileResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFile:getSourceFile", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceFile.
 */
export interface GetSourceFileArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFile.
 */
export interface GetSourceFileResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceFile DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceFile = airbyte.getSourceFile({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceFileOutput(args: GetSourceFileOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceFileResult> {
    return pulumi.output(args).apply((a: any) => getSourceFile(a, opts))
}

/**
 * A collection of arguments for invoking getSourceFile.
 */
export interface GetSourceFileOutputArgs {
    sourceId: pulumi.Input<string>;
}
