// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceLaunchdarkly DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceLaunchdarkly = airbyte.getSourceLaunchdarkly({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceLaunchdarkly(args: GetSourceLaunchdarklyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceLaunchdarklyResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceLaunchdarkly:getSourceLaunchdarkly", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceLaunchdarkly.
 */
export interface GetSourceLaunchdarklyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceLaunchdarkly.
 */
export interface GetSourceLaunchdarklyResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceLaunchdarkly DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceLaunchdarkly = airbyte.getSourceLaunchdarkly({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceLaunchdarklyOutput(args: GetSourceLaunchdarklyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceLaunchdarklyResult> {
    return pulumi.output(args).apply((a: any) => getSourceLaunchdarkly(a, opts))
}

/**
 * A collection of arguments for invoking getSourceLaunchdarkly.
 */
export interface GetSourceLaunchdarklyOutputArgs {
    sourceId: pulumi.Input<string>;
}
