// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceSftp DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceSftp = airbyte.getSourceSftp({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceSftp(args: GetSourceSftpArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSftpResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSftp:getSourceSftp", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceSftp.
 */
export interface GetSourceSftpArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSftp.
 */
export interface GetSourceSftpResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceSftp DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceSftp = airbyte.getSourceSftp({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceSftpOutput(args: GetSourceSftpOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceSftpResult> {
    return pulumi.output(args).apply((a: any) => getSourceSftp(a, opts))
}

/**
 * A collection of arguments for invoking getSourceSftp.
 */
export interface GetSourceSftpOutputArgs {
    sourceId: pulumi.Input<string>;
}
