// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceSpacexAPI DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceSpacexapi = airbyte.getSourceSpacexApi({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceSpacexApi(args: GetSourceSpacexApiArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSpacexApiResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSpacexApi:getSourceSpacexApi", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceSpacexApi.
 */
export interface GetSourceSpacexApiArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSpacexApi.
 */
export interface GetSourceSpacexApiResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceSpacexAPI DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceSpacexapi = airbyte.getSourceSpacexApi({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceSpacexApiOutput(args: GetSourceSpacexApiOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceSpacexApiResult> {
    return pulumi.output(args).apply((a: any) => getSourceSpacexApi(a, opts))
}

/**
 * A collection of arguments for invoking getSourceSpacexApi.
 */
export interface GetSourceSpacexApiOutputArgs {
    sourceId: pulumi.Input<string>;
}
