// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceDremio DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceDremio = airbyte.getSourceDremio({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceDremio(args: GetSourceDremioArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceDremioResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceDremio:getSourceDremio", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceDremio.
 */
export interface GetSourceDremioArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceDremio.
 */
export interface GetSourceDremioResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceDremio DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceDremio = airbyte.getSourceDremio({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceDremioOutput(args: GetSourceDremioOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceDremioResult> {
    return pulumi.output(args).apply((a: any) => getSourceDremio(a, opts))
}

/**
 * A collection of arguments for invoking getSourceDremio.
 */
export interface GetSourceDremioOutputArgs {
    sourceId: pulumi.Input<string>;
}
