// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceMailgun DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceMailgun = airbyte.getSourceMailgun({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceMailgun(args: GetSourceMailgunArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceMailgunResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceMailgun:getSourceMailgun", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceMailgun.
 */
export interface GetSourceMailgunArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceMailgun.
 */
export interface GetSourceMailgunResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceMailgun DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceMailgun = airbyte.getSourceMailgun({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceMailgunOutput(args: GetSourceMailgunOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceMailgunResult> {
    return pulumi.output(args).apply((a: any) => getSourceMailgun(a, opts))
}

/**
 * A collection of arguments for invoking getSourceMailgun.
 */
export interface GetSourceMailgunOutputArgs {
    sourceId: pulumi.Input<string>;
}
