// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceAuth0 DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceAuth0 = airbyte.getSourceAuth0({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceAuth0(args: GetSourceAuth0Args, opts?: pulumi.InvokeOptions): Promise<GetSourceAuth0Result> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAuth0:getSourceAuth0", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceAuth0.
 */
export interface GetSourceAuth0Args {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAuth0.
 */
export interface GetSourceAuth0Result {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceAuth0 DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceAuth0 = airbyte.getSourceAuth0({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceAuth0Output(args: GetSourceAuth0OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceAuth0Result> {
    return pulumi.output(args).apply((a: any) => getSourceAuth0(a, opts))
}

/**
 * A collection of arguments for invoking getSourceAuth0.
 */
export interface GetSourceAuth0OutputArgs {
    sourceId: pulumi.Input<string>;
}
