// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceFreshcaller DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceFreshcaller = airbyte.getSourceFreshcaller({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceFreshcaller(args: GetSourceFreshcallerArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFreshcallerResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFreshcaller:getSourceFreshcaller", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceFreshcaller.
 */
export interface GetSourceFreshcallerArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFreshcaller.
 */
export interface GetSourceFreshcallerResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceFreshcaller DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceFreshcaller = airbyte.getSourceFreshcaller({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceFreshcallerOutput(args: GetSourceFreshcallerOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceFreshcallerResult> {
    return pulumi.output(args).apply((a: any) => getSourceFreshcaller(a, opts))
}

/**
 * A collection of arguments for invoking getSourceFreshcaller.
 */
export interface GetSourceFreshcallerOutputArgs {
    sourceId: pulumi.Input<string>;
}
