// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceIntercom DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceIntercom = airbyte.getSourceIntercom({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceIntercom(args: GetSourceIntercomArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceIntercomResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceIntercom:getSourceIntercom", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceIntercom.
 */
export interface GetSourceIntercomArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceIntercom.
 */
export interface GetSourceIntercomResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceIntercom DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceIntercom = airbyte.getSourceIntercom({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceIntercomOutput(args: GetSourceIntercomOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceIntercomResult> {
    return pulumi.output(args).apply((a: any) => getSourceIntercom(a, opts))
}

/**
 * A collection of arguments for invoking getSourceIntercom.
 */
export interface GetSourceIntercomOutputArgs {
    sourceId: pulumi.Input<string>;
}
