// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceWikipediaPageviews DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceWikipediapageviews = airbyte.getSourceWikipediaPageviews({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceWikipediaPageviews(args: GetSourceWikipediaPageviewsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceWikipediaPageviewsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceWikipediaPageviews:getSourceWikipediaPageviews", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceWikipediaPageviews.
 */
export interface GetSourceWikipediaPageviewsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceWikipediaPageviews.
 */
export interface GetSourceWikipediaPageviewsResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceWikipediaPageviews DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceWikipediapageviews = airbyte.getSourceWikipediaPageviews({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceWikipediaPageviewsOutput(args: GetSourceWikipediaPageviewsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceWikipediaPageviewsResult> {
    return pulumi.output(args).apply((a: any) => getSourceWikipediaPageviews(a, opts))
}

/**
 * A collection of arguments for invoking getSourceWikipediaPageviews.
 */
export interface GetSourceWikipediaPageviewsOutputArgs {
    sourceId: pulumi.Input<string>;
}
