// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceZendeskChat DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceZendeskchat = airbyte.getSourceZendeskChat({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceZendeskChat(args: GetSourceZendeskChatArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceZendeskChatResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceZendeskChat:getSourceZendeskChat", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceZendeskChat.
 */
export interface GetSourceZendeskChatArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceZendeskChat.
 */
export interface GetSourceZendeskChatResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceZendeskChat DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceZendeskchat = airbyte.getSourceZendeskChat({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceZendeskChatOutput(args: GetSourceZendeskChatOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceZendeskChatResult> {
    return pulumi.output(args).apply((a: any) => getSourceZendeskChat(a, opts))
}

/**
 * A collection of arguments for invoking getSourceZendeskChat.
 */
export interface GetSourceZendeskChatOutputArgs {
    sourceId: pulumi.Input<string>;
}
