// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceSlack DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceSlack = airbyte.getSourceSlack({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceSlack(args: GetSourceSlackArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSlackResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSlack:getSourceSlack", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceSlack.
 */
export interface GetSourceSlackArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSlack.
 */
export interface GetSourceSlackResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceSlack DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceSlack = airbyte.getSourceSlack({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceSlackOutput(args: GetSourceSlackOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceSlackResult> {
    return pulumi.output(args).apply((a: any) => getSourceSlack(a, opts))
}

/**
 * A collection of arguments for invoking getSourceSlack.
 */
export interface GetSourceSlackOutputArgs {
    sourceId: pulumi.Input<string>;
}
