// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourcePolygonStockAPI DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourcePolygonstockapi = airbyte.getSourcePolygonStockApi({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourcePolygonStockApi(args: GetSourcePolygonStockApiArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePolygonStockApiResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePolygonStockApi:getSourcePolygonStockApi", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourcePolygonStockApi.
 */
export interface GetSourcePolygonStockApiArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePolygonStockApi.
 */
export interface GetSourcePolygonStockApiResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourcePolygonStockAPI DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourcePolygonstockapi = airbyte.getSourcePolygonStockApi({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourcePolygonStockApiOutput(args: GetSourcePolygonStockApiOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourcePolygonStockApiResult> {
    return pulumi.output(args).apply((a: any) => getSourcePolygonStockApi(a, opts))
}

/**
 * A collection of arguments for invoking getSourcePolygonStockApi.
 */
export interface GetSourcePolygonStockApiOutputArgs {
    sourceId: pulumi.Input<string>;
}
