// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceAha DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceAha = airbyte.getSourceAha({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceAha(args: GetSourceAhaArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAhaResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAha:getSourceAha", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceAha.
 */
export interface GetSourceAhaArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAha.
 */
export interface GetSourceAhaResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceAha DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceAha = airbyte.getSourceAha({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceAhaOutput(args: GetSourceAhaOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceAhaResult> {
    return pulumi.output(args).apply((a: any) => getSourceAha(a, opts))
}

/**
 * A collection of arguments for invoking getSourceAha.
 */
export interface GetSourceAhaOutputArgs {
    sourceId: pulumi.Input<string>;
}
