// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceAmazonSellerPartner DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceAmazonsellerpartner = airbyte.getSourceAmazonSellerPartner({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceAmazonSellerPartner(args: GetSourceAmazonSellerPartnerArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAmazonSellerPartnerResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAmazonSellerPartner:getSourceAmazonSellerPartner", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceAmazonSellerPartner.
 */
export interface GetSourceAmazonSellerPartnerArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAmazonSellerPartner.
 */
export interface GetSourceAmazonSellerPartnerResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceAmazonSellerPartner DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceAmazonsellerpartner = airbyte.getSourceAmazonSellerPartner({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceAmazonSellerPartnerOutput(args: GetSourceAmazonSellerPartnerOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceAmazonSellerPartnerResult> {
    return pulumi.output(args).apply((a: any) => getSourceAmazonSellerPartner(a, opts))
}

/**
 * A collection of arguments for invoking getSourceAmazonSellerPartner.
 */
export interface GetSourceAmazonSellerPartnerOutputArgs {
    sourceId: pulumi.Input<string>;
}
