// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourceSurveymonkey DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceSurveymonkey = airbyte.getSourceSurveymonkey({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceSurveymonkey(args: GetSourceSurveymonkeyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSurveymonkeyResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSurveymonkey:getSourceSurveymonkey", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourceSurveymonkey.
 */
export interface GetSourceSurveymonkeyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSurveymonkey.
 */
export interface GetSourceSurveymonkeyResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourceSurveymonkey DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourceSurveymonkey = airbyte.getSourceSurveymonkey({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourceSurveymonkeyOutput(args: GetSourceSurveymonkeyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceSurveymonkeyResult> {
    return pulumi.output(args).apply((a: any) => getSourceSurveymonkey(a, opts))
}

/**
 * A collection of arguments for invoking getSourceSurveymonkey.
 */
export interface GetSourceSurveymonkeyOutputArgs {
    sourceId: pulumi.Input<string>;
}
