// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SourcePrestashop DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourcePrestashop = airbyte.getSourcePrestashop({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourcePrestashop(args: GetSourcePrestashopArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePrestashopResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePrestashop:getSourcePrestashop", {
        "sourceId": args.sourceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSourcePrestashop.
 */
export interface GetSourcePrestashopArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePrestashop.
 */
export interface GetSourcePrestashopResult {
    /**
     * The values required to configure the source. Parsed as JSON.
     */
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
/**
 * SourcePrestashop DataSource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as airbyte from "@pulumi/airbyte";
 *
 * const mySourcePrestashop = airbyte.getSourcePrestashop({
 *     sourceId: "...my_source_id...",
 * });
 * ```
 */
export function getSourcePrestashopOutput(args: GetSourcePrestashopOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourcePrestashopResult> {
    return pulumi.output(args).apply((a: any) => getSourcePrestashop(a, opts))
}

/**
 * A collection of arguments for invoking getSourcePrestashop.
 */
export interface GetSourcePrestashopOutputArgs {
    sourceId: pulumi.Input<string>;
}
